apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: anagram-test-autoscaler
  namespace: anagram-test-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anagram-test
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90