apiVersion: v1
kind: Service
metadata:
  name: anagram-test-service
  namespace: anagram-test-dev
spec:
  selector:
    app: anagram-test
  type: LoadBalancer
  ports:
    - name: 'http'
      port: 8090
      protocol: 'TCP'
      targetPort: 8090