apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anagram-test-infrastructure

resources:
  - namespace.yaml
  - sonar/configmap-postgres-sonar.yaml
  - sonar/persistentvolumeclaim-postgres-sonar.yaml
  - sonar/deployment-postgres-sonar.yaml
  - sonar/service-postgres-sonar.yaml
  - sonar/configmap-sonar.yaml
  - sonar/persistentvolumeclaim-sonar.yaml
  - sonar/deployment-sonar.yaml
  - sonar/service-sonar.yaml