apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  namespace: anagram-test-infrastructure
spec:
  selector:
    app: sonar
  type: LoadBalancer
  ports:
    - name: 'http'
      port: 9000
      protocol: 'TCP'
      targetPort: 9000